## For students: change this path to the root of your code
CODEROOT = "/Users/soushimei/Dropbox/Courses/2014 Winter/222_Project/Project/FG7QJ378GJ292JFD"

#CC = gcc
CC = g++

#CPPFLAGS = -Wall -I$(CODEROOT) -O3  # maximal optimization
CPPFLAGS = -Wall -I$(CODEROOT) -g     # with debugging info
